### ISSUE TITLE
PDFで太字が潰れる

### ISSUE THREAD

**Issue by eggplants** [HelloRusk/marp-theme-academic#1]
```bash
# 潰れる
marp demo.md --pdf

# 潰れない
marp demo.md --images png && convert demo.*.png demo.pdf && rm demo.*.png
```

**Comment by eggplants** [comment]
marpの問題っぽいですが…

**Comment by kaisugi** [comment]
手元のローカルのM1 Macだと VSCode 版でも `npx marp ...` でも問題を再現できないです。すみません...

**Comment by kaisugi** [comment]
関係ないと思いますが、GitHub Actions で pdf と png を生成するワークフローにおいては、最初 npm パッケージの方で日本語フォントが表示されないという問題がありdockerイメージ版に切り替えたという経緯がありました。

**Comment by eggplants** [comment]
png
![image](https://user-images.githubusercontent.com/42153744/171859065-1132377f-a2a8-4d39-8396-07f7a03b712e.png)
pdf
![image](https://user-images.githubusercontent.com/42153744/171859466-af0b24f9-0661-45e7-8a92-9e4eeccbb3a7.png)

**Comment by eggplants** [comment]
環境はUbuntu 22.04です。

**Comment by kaisugi** [comment]
font-weight を700より小さい値に下げますかね...？

**Comment by kaisugi** [comment]
あー、

```css
strong {
  -webkit-text-stroke: 0.3px black;
}
```

がよくないきがしました。
これ、英語フォントの太字がやけに薄いなーと思ってつけたんですけど、フォント変えたのでいらない気がします。

**Comment by kaisugi** [comment]
↑の部分を消したらCI上ではマシになった感じがするので、お手元でもお確かめください。

<img width="1416" alt="スクリーンショット 2022-06-03 22 14 28" src="https://user-images.githubusercontent.com/36184621/171861311-ee5be528-afed-40a4-b694-75bec72ffbb1.png">

**Comment by eggplants** [comment]
解決しました！ありがとうございます🙏
