### ISSUE TITLE
Featuring this theme in a community-maintained theme gallery

### ISSUE THREAD

**Issue by rnd195** [HelloRusk/marp-theme-academic#2]
Hi,

I am building a community-maintained theme gallery for Marp [here on GitHub](https://github.com/rnd195/marp-community-themes), and I'd like to feature your theme. Before that, however, I wanted to reach out to ask whether it would be alright with you if I were to add your project to the gallery (with proper attribution, of course).

To get a sense of what the feature would look like, please, take a look at one of the showcased themes (e.g., [graph_paper](https://rnd195.github.io/marp-community-themes/theme/graph_paper.html)). The gallery currently contains only four of my own themes, but I am in the process of contacting other creators and asking them about featuring their work, too. As you may find, I provide links to the original repository of the theme and the author's GitHub page (or personal website) for attribution.

Many thanks for your consideration and feedback.

Martin

**Comment by kaisugi** [comment]
Hi, it's totally fine to introduce my theme!

**Comment by rnd195** [comment]
Great, thanks! I'll add your theme in the very near future. Closing the issue.
